name: deploy

on:
  push:
    tags: 
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Livraison ${{ github.event_name }}
        uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          CLI: gsutil
        with:
          args: rsync -R public gs://${{ secrets.GOOGLE_BUCKET_NAME }}
